Student and StudentCourse
MbusoKotobe/college-management-system pull request #95
Opened 2022-04-08 18:58 UTC by AIsmail-git

…ositories regarding Student and StudentCourse entities and tested it

2022-04-08 20:05 UTC, MbusoKotobe commented on src/main/java/za/ac/cput/utility/Helper.java
> +    public static String generateId()
How do you feel about removing the generateId method?
I saw that its not being used anywhere.

2022-04-08 20:06 UTC, MbusoKotobe approved these changes

2022-04-08 20:16 UTC, MbusoKotobe requested changes
Why is a name of a student being assigned an ID???

Please fix that.

2022-04-09 14:12 UTC, JayKuzi requested changes
Ensure that target folder is being ignored and not in your pull request, also follow Mbuso's review request.

2022-04-10 14:44 UTC, merged